language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token_commercify
  
  on:
    branch: server
env: 
  - TEST_MONGODBURI=$TEST_MONGODBURI
  - JWT_SECRET_KEY=$JWT_SECRET_KEY